apiVersion: skaffold/v1
kind: Config
metadata:
  name: job-status-listener
deploy:
  kubectl:
    manifests:
    - k8s/job-status-listener.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: discoenv/job-status-listener
  local: {}
